version: '3.8'
services:
  
  # # localhost:3000
  # node_microservice:
  #   build: ./node_microservice
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork

  # # localhost:8000/docs
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  # # localhost:4200
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - mynetwork

  # localhost:27017
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27317:27017" # Avoid port conflict with local mongodb
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: db_repos # creates a new db

volumes:
  mongodb_data_container: {}

networks:
  mynetwork:

# To build the services
# docker-compose up --build