version: '3.8'
services:
  
  # # localhost:3000
  # node_microservice:
  #   build: ./node_microservice
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork

  # # localhost:8000/docs
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - mynetwork

  # # localhost:4200
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "4200:80"
  #   networks:
  #     - mynetwork

  # localhost:27017
  mongo:
    image: mongo
    ports:
      - "27117:27017"
    networks:
      - mynetwork

networks:
  mynetwork:

# To build the services
# docker-compose up --build